package PRIAM_LANGUAGE.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DataSubject_Constraints extends BaseConstraintsDescriptor {
  public DataSubject_Constraints() {
    super(CONCEPTS.DataSubject$Ol);
  }

  public static class Age_Property extends BasePropertyConstraintsDescriptor {
    public Age_Property(ConstraintsDescriptor container) {
      super(PROPS.age$k8JX, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:1dfc30dd-a369-40c9-b654-fedeab4cc8c4(PRIAM_LANGUAGE.constraints)", "4400862896331979027"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return SPropertyOperations.getInteger(node, PROPS.age$k8JX) >= 0;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.age$k8JX, new Age_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataSubject$Ol = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL, "PRIAM_LANGUAGE.structure.DataSubject");
  }

  private static final class PROPS {
    /*package*/ static final SProperty age$k8JX = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL, 0x30f0048592d2bdb3L, "age");
  }
}
