package PRIAM_LANGUAGE.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myDataType__BehaviorDescriptor = new DataType__BehaviorDescriptor();
  private final BHDescriptor myPersonalData__BehaviorDescriptor = new PersonalData__BehaviorDescriptor();
  private final BHDescriptor myNonPersonalData__BehaviorDescriptor = new NonPersonalData__BehaviorDescriptor();
  private final BHDescriptor myAddress__BehaviorDescriptor = new Address__BehaviorDescriptor();
  private final BHDescriptor myActor__BehaviorDescriptor = new Actor__BehaviorDescriptor();
  private final BHDescriptor myDataAnnotation__BehaviorDescriptor = new DataAnnotation__BehaviorDescriptor();
  private final BHDescriptor myProcessing__BehaviorDescriptor = new Processing__BehaviorDescriptor();
  private final BHDescriptor myData__BehaviorDescriptor = new Data__BehaviorDescriptor();
  private final BHDescriptor myDataUsage__BehaviorDescriptor = new DataUsage__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myActor__BehaviorDescriptor;
      case 1:
        return myAddress__BehaviorDescriptor;
      case 2:
        return myData__BehaviorDescriptor;
      case 3:
        return myDataAnnotation__BehaviorDescriptor;
      case 4:
        return myDataType__BehaviorDescriptor;
      case 5:
        return myDataUsage__BehaviorDescriptor;
      case 6:
        return myNonPersonalData__BehaviorDescriptor;
      case 7:
        return myPersonalData__BehaviorDescriptor;
      case 8:
        return myProcessing__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x3af6325cd45a5aa2L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5309b4b3bd5290L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411277L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2615d150e803c810L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x9b6693a01c08cc8L), MetaIdFactory.conceptId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L)).seal();
}
