package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AdType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AdType() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x47902e7b5e4f4b63L, "AdType", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5156672680737327971");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Yes_0 = new EnumerationDescriptor.MemberDescriptor("Yes", "Yes", 0x47902e7b5e4f4b64L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5156672680737327972");
  private final EnumerationDescriptor.MemberDescriptor myMember_Partial_0 = new EnumerationDescriptor.MemberDescriptor("Partial", "Partial", 0x47902e7b5e4f4b65L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5156672680737327973");
  private final EnumerationDescriptor.MemberDescriptor myMember_No_0 = new EnumerationDescriptor.MemberDescriptor("No", "No", 0x47902e7b5e4f4b68L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5156672680737327976");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x47902e7b5e4f4b63L, 0x47902e7b5e4f4b64L, 0x47902e7b5e4f4b65L, 0x47902e7b5e4f4b68L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Yes_0, myMember_Partial_0, myMember_No_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Yes":
        return myMember_Yes_0;
      case "Partial":
        return myMember_Partial_0;
      case "No":
        return myMember_No_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
