package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ProcessingRequestType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ProcessingRequestType() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x9fd0368595e077aL, "ProcessingRequestType", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/719735262159964026");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Objection_0 = new EnumerationDescriptor.MemberDescriptor("Objection", "Objection", 0x9fd0368595e077bL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/719735262159964027");
  private final EnumerationDescriptor.MemberDescriptor myMember_Restriction_0 = new EnumerationDescriptor.MemberDescriptor("Restriction", "Restriction", 0x9fd0368595e077cL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/719735262159964028");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x9fd0368595e077aL, 0x9fd0368595e077bL, 0x9fd0368595e077cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Objection_0, myMember_Restriction_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Objection":
        return myMember_Objection_0;
      case "Restriction":
        return myMember_Restriction_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
