package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_LinkType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LinkType() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb2db895bL, "LinkType", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262449199451");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_SimilarityLink_0 = new EnumerationDescriptor.MemberDescriptor("SimilarityLink", "SimilarityLink", 0x1f97ffaeb2db895cL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262449199452");
  private final EnumerationDescriptor.MemberDescriptor myMember_InclusionLink_0 = new EnumerationDescriptor.MemberDescriptor("InclusionLink", "InclusionLink", 0x1f97ffaeb2db895dL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262449199453");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb2db895bL, 0x1f97ffaeb2db895cL, 0x1f97ffaeb2db895dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_SimilarityLink_0, myMember_InclusionLink_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "SimilarityLink":
        return myMember_SimilarityLink_0;
      case "InclusionLink":
        return myMember_InclusionLink_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
