package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Risk extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Risk() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb111747279c87eL, "Risk", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391167383678");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NORISK_0 = new EnumerationDescriptor.MemberDescriptor("NORISK", "NORISK", 0xcb111747279c87fL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391167383679");
  private final EnumerationDescriptor.MemberDescriptor myMember_AVERAGE_0 = new EnumerationDescriptor.MemberDescriptor("AVERAGE", "AVERAGE", 0xcb111747279c880L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391167383680");
  private final EnumerationDescriptor.MemberDescriptor myMember_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "HIGH", 0xcb111747279c883L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391167383683");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb111747279c87eL, 0xcb111747279c87fL, 0xcb111747279c880L, 0xcb111747279c883L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NORISK_0, myMember_AVERAGE_0, myMember_HIGH_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NORISK":
        return myMember_NORISK_0;
      case "AVERAGE":
        return myMember_AVERAGE_0;
      case "HIGH":
        return myMember_HIGH_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
