package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SecondaryActorType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SecondaryActorType() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e675L, "SecondaryActorType", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6986923738720036469");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DataConsumer_0 = new EnumerationDescriptor.MemberDescriptor("DataConsumer", "DataConsumer", 0x60f68a1f3f26e676L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6986923738720036470");
  private final EnumerationDescriptor.MemberDescriptor myMember_DataProcessor_0 = new EnumerationDescriptor.MemberDescriptor("DataProcessor", "DataProcessor", 0x60f68a1f3f26e677L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6986923738720036471");
  private final EnumerationDescriptor.MemberDescriptor myMember_ThirdParty_0 = new EnumerationDescriptor.MemberDescriptor("ThirdParty", "ThirdParty", 0x60f68a1f3f26e67aL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6986923738720036474");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e675L, 0x60f68a1f3f26e676L, 0x60f68a1f3f26e677L, 0x60f68a1f3f26e67aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_DataConsumer_0, myMember_DataProcessor_0, myMember_ThirdParty_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DataConsumer":
        return myMember_DataConsumer_0;
      case "DataProcessor":
        return myMember_DataProcessor_0;
      case "ThirdParty":
        return myMember_ThirdParty_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
