package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Source extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Source() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5547fb75b03f47d2L, "Source", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6145156699457013714");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Direct_0 = new EnumerationDescriptor.MemberDescriptor("Direct", "Direct", 0x5547fb75b03f47d3L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6145156699457013715");
  private final EnumerationDescriptor.MemberDescriptor myMember_Indirect_0 = new EnumerationDescriptor.MemberDescriptor("Indirect", "Indirect", 0x5547fb75b03f47d4L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6145156699457013716");
  private final EnumerationDescriptor.MemberDescriptor myMember_Generated_0 = new EnumerationDescriptor.MemberDescriptor("Generated", "Generated", 0x5547fb75b03f47d7L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6145156699457013719");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5547fb75b03f47d2L, 0x5547fb75b03f47d3L, 0x5547fb75b03f47d4L, 0x5547fb75b03f47d7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Direct_0, myMember_Indirect_0, myMember_Generated_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Direct_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Direct":
        return myMember_Direct_0;
      case "Indirect":
        return myMember_Indirect_0;
      case "Generated":
        return myMember_Generated_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
