package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SafeguardType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SafeguardType() {
    super(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451c5L, "SafeguardType", "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342021");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AdequacyDecision_0 = new EnumerationDescriptor.MemberDescriptor("AdequacyDecision", "AdequacyDecision", 0x2a509229fff451d1L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342033");
  private final EnumerationDescriptor.MemberDescriptor myMember_ContractualClauses_0 = new EnumerationDescriptor.MemberDescriptor("ContractualClauses", "ContractualClauses", 0x2a509229fff451d3L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342035");
  private final EnumerationDescriptor.MemberDescriptor myMember_Derogation_0 = new EnumerationDescriptor.MemberDescriptor("Derogation", "Derogation", 0x2a509229fff451d6L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342038");
  private final EnumerationDescriptor.MemberDescriptor myMember_BCR_0 = new EnumerationDescriptor.MemberDescriptor("BCR", "BCR", 0x2a509229fff451daL, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342042");
  private final EnumerationDescriptor.MemberDescriptor myMember_No_0 = new EnumerationDescriptor.MemberDescriptor("No", "No", 0x1b92547a1d81c2b5L, "r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/1986743269081596597");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451c5L, 0x2a509229fff451d1L, 0x2a509229fff451d3L, 0x2a509229fff451d6L, 0x2a509229fff451daL, 0x1b92547a1d81c2b5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_AdequacyDecision_0, myMember_ContractualClauses_0, myMember_Derogation_0, myMember_BCR_0, myMember_No_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_No_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AdequacyDecision":
        return myMember_AdequacyDecision_0;
      case "ContractualClauses":
        return myMember_ContractualClauses_0;
      case "Derogation":
        return myMember_Derogation_0;
      case "BCR":
        return myMember_BCR_0;
      case "No":
        return myMember_No_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
