package PRIAM_LANGUAGE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActor = createDescriptorForActor();
  /*package*/ final ConceptDescriptor myConceptActorAnnotation = createDescriptorForActorAnnotation();
  /*package*/ final ConceptDescriptor myConceptAddress = createDescriptorForAddress();
  /*package*/ final ConceptDescriptor myConceptBreach = createDescriptorForBreach();
  /*package*/ final ConceptDescriptor myConceptConsent = createDescriptorForConsent();
  /*package*/ final ConceptDescriptor myConceptConsequence = createDescriptorForConsequence();
  /*package*/ final ConceptDescriptor myConceptContract = createDescriptorForContract();
  /*package*/ final ConceptDescriptor myConceptCountry = createDescriptorForCountry();
  /*package*/ final ConceptDescriptor myConceptDPO = createDescriptorForDPO();
  /*package*/ final ConceptDescriptor myConceptData = createDescriptorForData();
  /*package*/ final ConceptDescriptor myConceptDataAnnotation = createDescriptorForDataAnnotation();
  /*package*/ final ConceptDescriptor myConceptDataAnswer = createDescriptorForDataAnswer();
  /*package*/ final ConceptDescriptor myConceptDataRef = createDescriptorForDataRef();
  /*package*/ final ConceptDescriptor myConceptDataRequest = createDescriptorForDataRequest();
  /*package*/ final ConceptDescriptor myConceptDataRequestAnswer = createDescriptorForDataRequestAnswer();
  /*package*/ final ConceptDescriptor myConceptDataSubject = createDescriptorForDataSubject();
  /*package*/ final ConceptDescriptor myConceptDataSubjectCategory = createDescriptorForDataSubjectCategory();
  /*package*/ final ConceptDescriptor myConceptDataSubjectRef = createDescriptorForDataSubjectRef();
  /*package*/ final ConceptDescriptor myConceptDataType = createDescriptorForDataType();
  /*package*/ final ConceptDescriptor myConceptDataUsage = createDescriptorForDataUsage();
  /*package*/ final ConceptDescriptor myConceptListCountry = createDescriptorForListCountry();
  /*package*/ final ConceptDescriptor myConceptListPersonalDataCategory = createDescriptorForListPersonalDataCategory();
  /*package*/ final ConceptDescriptor myConceptMainActor = createDescriptorForMainActor();
  /*package*/ final ConceptDescriptor myConceptMainActorRef = createDescriptorForMainActorRef();
  /*package*/ final ConceptDescriptor myConceptMeasure = createDescriptorForMeasure();
  /*package*/ final ConceptDescriptor myConceptMeasureRef = createDescriptorForMeasureRef();
  /*package*/ final ConceptDescriptor myConceptNonPersonalData = createDescriptorForNonPersonalData();
  /*package*/ final ConceptDescriptor myConceptPRIAM_DB = createDescriptorForPRIAM_DB();
  /*package*/ final ConceptDescriptor myConceptPersonalData = createDescriptorForPersonalData();
  /*package*/ final ConceptDescriptor myConceptPersonalDataCategory = createDescriptorForPersonalDataCategory();
  /*package*/ final ConceptDescriptor myConceptPersonalDataTransfer = createDescriptorForPersonalDataTransfer();
  /*package*/ final ConceptDescriptor myConceptProcessing = createDescriptorForProcessing();
  /*package*/ final ConceptDescriptor myConceptProcessingAnnotation = createDescriptorForProcessingAnnotation();
  /*package*/ final ConceptDescriptor myConceptProcessingLink = createDescriptorForProcessingLink();
  /*package*/ final ConceptDescriptor myConceptProcessingRef = createDescriptorForProcessingRef();
  /*package*/ final ConceptDescriptor myConceptProcessingRequest = createDescriptorForProcessingRequest();
  /*package*/ final ConceptDescriptor myConceptProvider = createDescriptorForProvider();
  /*package*/ final ConceptDescriptor myConceptPurpose = createDescriptorForPurpose();
  /*package*/ final ConceptDescriptor myConceptRepresentative = createDescriptorForRepresentative();
  /*package*/ final ConceptDescriptor myConceptRequest = createDescriptorForRequest();
  /*package*/ final ConceptDescriptor myConceptRequirements = createDescriptorForRequirements();
  /*package*/ final ConceptDescriptor myConceptSecondaryActor = createDescriptorForSecondaryActor();
  /*package*/ final ConceptDescriptor myConceptSecondaryActorCategory = createDescriptorForSecondaryActorCategory();
  /*package*/ final ConceptDescriptor myConceptSecondaryActorRef = createDescriptorForSecondaryActorRef();
  /*package*/ final ConceptDescriptor myConceptTutor = createDescriptorForTutor();
  /*package*/ final EnumerationDescriptor myEnumerationAdType = new EnumerationDescriptor_AdType();
  /*package*/ final EnumerationDescriptor myEnumerationCategoryMeasure = new EnumerationDescriptor_CategoryMeasure();
  /*package*/ final EnumerationDescriptor myEnumerationLinkType = new EnumerationDescriptor_LinkType();
  /*package*/ final EnumerationDescriptor myEnumerationProcessingCategory = new EnumerationDescriptor_ProcessingCategory();
  /*package*/ final EnumerationDescriptor myEnumerationProcessingRequestType = new EnumerationDescriptor_ProcessingRequestType();
  /*package*/ final EnumerationDescriptor myEnumerationProcessingType = new EnumerationDescriptor_ProcessingType();
  /*package*/ final EnumerationDescriptor myEnumerationPurposeType = new EnumerationDescriptor_PurposeType();
  /*package*/ final EnumerationDescriptor myEnumerationRisk = new EnumerationDescriptor_Risk();
  /*package*/ final EnumerationDescriptor myEnumerationSafeguardType = new EnumerationDescriptor_SafeguardType();
  /*package*/ final EnumerationDescriptor myEnumerationSecondaryActorType = new EnumerationDescriptor_SecondaryActorType();
  /*package*/ final EnumerationDescriptor myEnumerationSource = new EnumerationDescriptor_Source();
  /*package*/ final EnumerationDescriptor myEnumerationTypeDataRequest = new EnumerationDescriptor_TypeDataRequest();
  /*package*/ final EnumerationDescriptor myEnumerationTypeMeasure = new EnumerationDescriptor_TypeMeasure();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActor, myConceptActorAnnotation, myConceptAddress, myConceptBreach, myConceptConsent, myConceptConsequence, myConceptContract, myConceptCountry, myConceptDPO, myConceptData, myConceptDataAnnotation, myConceptDataAnswer, myConceptDataRef, myConceptDataRequest, myConceptDataRequestAnswer, myConceptDataSubject, myConceptDataSubjectCategory, myConceptDataSubjectRef, myConceptDataType, myConceptDataUsage, myConceptListCountry, myConceptListPersonalDataCategory, myConceptMainActor, myConceptMainActorRef, myConceptMeasure, myConceptMeasureRef, myConceptNonPersonalData, myConceptPRIAM_DB, myConceptPersonalData, myConceptPersonalDataCategory, myConceptPersonalDataTransfer, myConceptProcessing, myConceptProcessingAnnotation, myConceptProcessingLink, myConceptProcessingRef, myConceptProcessingRequest, myConceptProvider, myConceptPurpose, myConceptRepresentative, myConceptRequest, myConceptRequirements, myConceptSecondaryActor, myConceptSecondaryActorCategory, myConceptSecondaryActorRef, myConceptTutor);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actor:
        return myConceptActor;
      case LanguageConceptSwitch.ActorAnnotation:
        return myConceptActorAnnotation;
      case LanguageConceptSwitch.Address:
        return myConceptAddress;
      case LanguageConceptSwitch.Breach:
        return myConceptBreach;
      case LanguageConceptSwitch.Consent:
        return myConceptConsent;
      case LanguageConceptSwitch.Consequence:
        return myConceptConsequence;
      case LanguageConceptSwitch.Contract:
        return myConceptContract;
      case LanguageConceptSwitch.Country:
        return myConceptCountry;
      case LanguageConceptSwitch.DPO:
        return myConceptDPO;
      case LanguageConceptSwitch.Data:
        return myConceptData;
      case LanguageConceptSwitch.DataAnnotation:
        return myConceptDataAnnotation;
      case LanguageConceptSwitch.DataAnswer:
        return myConceptDataAnswer;
      case LanguageConceptSwitch.DataRef:
        return myConceptDataRef;
      case LanguageConceptSwitch.DataRequest:
        return myConceptDataRequest;
      case LanguageConceptSwitch.DataRequestAnswer:
        return myConceptDataRequestAnswer;
      case LanguageConceptSwitch.DataSubject:
        return myConceptDataSubject;
      case LanguageConceptSwitch.DataSubjectCategory:
        return myConceptDataSubjectCategory;
      case LanguageConceptSwitch.DataSubjectRef:
        return myConceptDataSubjectRef;
      case LanguageConceptSwitch.DataType:
        return myConceptDataType;
      case LanguageConceptSwitch.DataUsage:
        return myConceptDataUsage;
      case LanguageConceptSwitch.ListCountry:
        return myConceptListCountry;
      case LanguageConceptSwitch.ListPersonalDataCategory:
        return myConceptListPersonalDataCategory;
      case LanguageConceptSwitch.MainActor:
        return myConceptMainActor;
      case LanguageConceptSwitch.MainActorRef:
        return myConceptMainActorRef;
      case LanguageConceptSwitch.Measure:
        return myConceptMeasure;
      case LanguageConceptSwitch.MeasureRef:
        return myConceptMeasureRef;
      case LanguageConceptSwitch.NonPersonalData:
        return myConceptNonPersonalData;
      case LanguageConceptSwitch.PRIAM_DB:
        return myConceptPRIAM_DB;
      case LanguageConceptSwitch.PersonalData:
        return myConceptPersonalData;
      case LanguageConceptSwitch.PersonalDataCategory:
        return myConceptPersonalDataCategory;
      case LanguageConceptSwitch.PersonalDataTransfer:
        return myConceptPersonalDataTransfer;
      case LanguageConceptSwitch.Processing:
        return myConceptProcessing;
      case LanguageConceptSwitch.ProcessingAnnotation:
        return myConceptProcessingAnnotation;
      case LanguageConceptSwitch.ProcessingLink:
        return myConceptProcessingLink;
      case LanguageConceptSwitch.ProcessingRef:
        return myConceptProcessingRef;
      case LanguageConceptSwitch.ProcessingRequest:
        return myConceptProcessingRequest;
      case LanguageConceptSwitch.Provider:
        return myConceptProvider;
      case LanguageConceptSwitch.Purpose:
        return myConceptPurpose;
      case LanguageConceptSwitch.Representative:
        return myConceptRepresentative;
      case LanguageConceptSwitch.Request:
        return myConceptRequest;
      case LanguageConceptSwitch.Requirements:
        return myConceptRequirements;
      case LanguageConceptSwitch.SecondaryActor:
        return myConceptSecondaryActor;
      case LanguageConceptSwitch.SecondaryActorCategory:
        return myConceptSecondaryActorCategory;
      case LanguageConceptSwitch.SecondaryActorRef:
        return myConceptSecondaryActorRef;
      case LanguageConceptSwitch.Tutor:
        return myConceptTutor;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationAdType, myEnumerationCategoryMeasure, myEnumerationLinkType, myEnumerationProcessingCategory, myEnumerationProcessingRequestType, myEnumerationProcessingType, myEnumerationPurposeType, myEnumerationRisk, myEnumerationSafeguardType, myEnumerationSecondaryActorType, myEnumerationSource, myEnumerationTypeDataRequest, myEnumerationTypeMeasure);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Actor", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L);
    b.class_(false, true, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544488");
    b.version(3);
    b.property("actorId", 0x3f0ad7c4153c99b7L).type(PrimitiveTypeId.INTEGER).origin("4542680411326421431").done();
    b.associate("country", 0x5e5ebbabb1377b6dL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b5dL).optional(false).origin("6800078833463032685").done();
    b.alias("actor");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActorAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ActorAnnotation", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342110");
    b.version(3);
    b.aggregate("provider", 0x2a509229fff4522dL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdacL).optional(false).ordered(true).multiple(false).origin("3049097656815342125").done();
    b.aggregate("dpo", 0x2a509229fff4523fL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b6fL).optional(true).ordered(true).multiple(false).origin("3049097656815342143").done();
    b.aggregate("representative", 0x2a509229fff45246L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff45205L).optional(true).ordered(true).multiple(false).origin("3049097656815342150").done();
    b.aggregate("dataSubjectCategories", 0x2a509229fff45221L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL).optional(false).ordered(true).multiple(true).origin("3049097656815342113").done();
    b.aggregate("secodaryActorCategories", 0x2a509229fff45224L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL).optional(true).ordered(true).multiple(true).origin("3049097656815342116").done();
    b.aggregate("secondaryActors", 0x2a509229fff45228L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL).optional(true).ordered(true).multiple(true).origin("3049097656815342120").done();
    b.alias("actorAnnotation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAddress() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Address", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342006");
    b.version(3);
    b.property("addressId", 0x13b7d32444879362L).type(PrimitiveTypeId.INTEGER).origin("1420836360180700002").done();
    b.property("streetNumber", 0x718a863b65af79ecL).type(PrimitiveTypeId.INTEGER).origin("8181499262739118572").done();
    b.property("streetName", 0x718a863b65af79f0L).type(PrimitiveTypeId.STRING).origin("8181499262739118576").done();
    b.property("PostalCode", 0x5e5ebbabb1377b4bL).type(PrimitiveTypeId.STRING).origin("6800078833463032651").done();
    b.property("city", 0x5e5ebbabb1377b4cL).type(PrimitiveTypeId.STRING).origin("6800078833463032652").done();
    b.property("complement", 0x718a863b65af79f5L).type(PrimitiveTypeId.STRING).origin("8181499262739118581").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBreach() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Breach", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb1117472736f9cL);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391166967708");
    b.version(3);
    b.property("breachId", 0xcb111747279c887L).type(PrimitiveTypeId.INTEGER).origin("914531391167383687").done();
    b.property("nature", 0xcb111747279c889L).type(PrimitiveTypeId.STRING).origin("914531391167383689").done();
    b.property("riskLevel", 0xcb111747279c88cL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb111747279c87eL)).origin("914531391167383692").done();
    b.property("createdAt", 0xcb111747279c890L).type(PrimitiveTypeId.INTEGER).origin("914531391167383696").done();
    b.property("sprvAuthNonNotifReasons", 0xcb111747279c895L).type(PrimitiveTypeId.STRING).origin("914531391167383701").done();
    b.property("dataSubjNonNotifReasons", 0xcb111747279c89bL).type(PrimitiveTypeId.STRING).origin("914531391167383707").done();
    b.aggregate("consequences", 0xcb111747279c8adL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb111747274a413L).optional(false).ordered(true).multiple(true).origin("914531391167383725").done();
    b.aggregate("data", 0xcb111747279c8b1L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bb9471dL).optional(false).ordered(true).multiple(true).origin("914531391167383729").done();
    b.aggregate("measures", 0xcb111747279c8b4L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e7c5L).optional(true).ordered(true).multiple(true).origin("914531391167383732").done();
    b.aggregate("dataSubject", 0xcb111747279c8b8L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL).optional(false).ordered(true).multiple(true).origin("914531391167383736").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConsent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Consent", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411215L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656832533");
    b.version(3);
    b.property("consentId", 0x13b7d3244487936bL).type(PrimitiveTypeId.INTEGER).origin("1420836360180700011").done();
    b.property("startDate", 0x5ed7b73b7b411264L).type(PrimitiveTypeId.STRING).origin("6834132425656832612").done();
    b.property("endDate", 0x5ed7b73b7b411266L).type(PrimitiveTypeId.STRING).origin("6834132425656832614").done();
    b.aggregate("processing", 0x5ed7b73b7b411245L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x26e217bc0d00c73dL).optional(false).ordered(true).multiple(false).origin("6834132425656832581").done();
    b.alias("consent");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConsequence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Consequence", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0xcb111747274a413L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/914531391167046675");
    b.version(3);
    b.property("impactId", 0xcb111747279c8a2L).type(PrimitiveTypeId.INTEGER).origin("914531391167383714").done();
    b.property("description", 0xcb111747279c8a4L).type(PrimitiveTypeId.STRING).origin("914531391167383716").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContract() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Contract", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b4089d2L);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656797650");
    b.version(3);
    b.property("contractId", 0x3f0ad7c415526899L).type(PrimitiveTypeId.INTEGER).origin("4542680411327850649").done();
    b.property("Signaturedate", 0x5ed7b73b7b4089d5L).type(PrimitiveTypeId.STRING).origin("6834132425656797653").done();
    b.property("Expirationdate", 0x5ed7b73b7b4089f5L).type(PrimitiveTypeId.STRING).origin("6834132425656797685").done();
    b.aggregate("consent", 0x5ed7b73b7b411240L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411215L).optional(false).ordered(true).multiple(true).origin("6834132425656832576").done();
    b.aggregate("dataSubjectRef", 0x1f97ffaeb30c0a84L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb30c0a81L).optional(false).ordered(true).multiple(false).origin("2276569262452378244").done();
    b.alias("contract");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCountry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Country", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b5dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6800078833463032669");
    b.version(3);
    b.property("countryId", 0x5e5ebbabb1377b60L).type(PrimitiveTypeId.INTEGER).origin("6800078833463032672").done();
    b.property("minorAge", 0x5e5ebbabb1377b65L).type(PrimitiveTypeId.INTEGER).origin("6800078833463032677").done();
    b.property("adequate", 0x1f97ffaeb2ca28e2L).type(PrimitiveTypeId.BOOLEAN).origin("2276569262448060642").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDPO() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DPO", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b6fL);
    b.class_(false, false, false);
    // extends: PRIAM_LANGUAGE.structure.MainActor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6800078833463032687");
    b.version(3);
    b.property("dpoPhone", 0x5e5ebbabb1377b74L).type(PrimitiveTypeId.STRING).origin("6800078833463032692").done();
    b.property("dpoEmail", 0x5e5ebbabb1377b75L).type(PrimitiveTypeId.STRING).origin("6800078833463032693").done();
    b.aggregate("dpoAddress", 0x2a509229fff451fdL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L).optional(false).ordered(true).multiple(false).origin("3049097656815342077").done();
    b.alias("DPO");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForData() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Data", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656832617");
    b.version(3);
    b.property("dataId", 0x3f0ad7c4155b8e68L).type(PrimitiveTypeId.INTEGER).origin("4542680411328450152").done();
    b.property("primaryKey", 0x3c40a36f20d51f14L).type(PrimitiveTypeId.BOOLEAN).origin("4341649738472693524").done();
    b.property("dataConservation", 0x1f97ffaeb2ce777dL).type(PrimitiveTypeId.STRING).origin("2276569262448342909").done();
    b.property("source", 0x1f97ffaeb2ce777eL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5547fb75b03f47d2L)).origin("2276569262448342910").done();
    b.property("sourceDetails", 0x1f97ffaeb2ce777fL).type(PrimitiveTypeId.STRING).origin("2276569262448342911").done();
    b.property("isPortable", 0x1f97ffaeb2ce7780L).type(PrimitiveTypeId.BOOLEAN).origin("2276569262448342912").done();
    b.property("isPersonal", 0x1f97ffaeb2ce7779L).type(PrimitiveTypeId.BOOLEAN).origin("2276569262448342905").done();
    b.associate("personalDataCategory", 0x1f97ffaeb2ce7788L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a4L).optional(true).origin("2276569262448342920").done();
    b.associate("dataSubjectCategory", 0x1f97ffaeb2ce7789L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL).optional(true).origin("2276569262448342921").done();
    b.alias("data");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataAnnotation", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x3af6325cd45a5aa2L);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/4248638672751712930");
    b.version(3);
    b.aggregate("personaldataCategories", 0x3c40a36f20cc9aabL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a4L).optional(false).ordered(true).multiple(true).origin("4341649738472135339").done();
    b.aggregate("dataType", 0x3af6325cd45a5aa3L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5309b4b3bd5290L).optional(false).ordered(true).multiple(true).origin("4248638672751712931").done();
    b.alias("dataAnnotation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataAnswer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataAnswer", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x13b7d324448cf27aL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/1420836360181052026");
    b.version(3);
    b.property("answerByData", 0x13b7d324448cf27bL).type(PrimitiveTypeId.BOOLEAN).origin("1420836360181052027").done();
    b.associate("dataReq", 0x13b7d324448cf287L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96e9L).optional(false).origin("1420836360181052039").done();
    b.associate("data", 0x13b7d324448cf289L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L).optional(false).origin("1420836360181052041").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bb9471dL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/9086395038182229789");
    b.version(3);
    b.associate("dataRef", 0x7e195c253bb94720L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L).optional(false).origin("9086395038182229792").done();
    b.alias("data");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataRequest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataRequest", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96e9L);
    b.class_(false, false, true);
    // extends: PRIAM_LANGUAGE.structure.Request
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96d3L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/4648915867537282793");
    b.version(3);
    b.property("newValue", 0x40844459bb3c96eeL).type(PrimitiveTypeId.STRING).origin("4648915867537282798").done();
    b.property("isIsolated", 0x2e89ca20e06e75b3L).type(PrimitiveTypeId.BOOLEAN).origin("3353433640107144627").done();
    b.property("type", 0x507d8789e719e8bdL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e719e8c1L)).origin("5799940921480571069").done();
    b.associate("datasubject", 0x507d8789e719e8a4L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL).optional(false).origin("5799940921480571044").done();
    b.aggregate("data", 0x13b7d324448cf282L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bb9471dL).optional(false).ordered(true).multiple(true).origin("1420836360181052034").done();
    b.alias("dataRequest");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataRequestAnswer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataRequestAnswer", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x3f0ad7c4153e7cfeL);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/4542680411326545150");
    b.version(3);
    b.property("id", 0x3f0ad7c4153e7cffL).type(PrimitiveTypeId.INTEGER).origin("4542680411326545151").done();
    b.property("answer", 0x3f0ad7c4153e7d01L).type(PrimitiveTypeId.BOOLEAN).origin("4542680411326545153").done();
    b.property("answerDate", 0x25afccdadf83e33L).type(PrimitiveTypeId.STRING).origin("169725896297037363").done();
    b.property("proof", 0x3f0ad7c4153e7d06L).type(PrimitiveTypeId.STRING).origin("4542680411326545158").done();
    b.associate("request", 0x3f0ad7c4153e7d04L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96e9L).optional(false).origin("4542680411326545156").done();
    b.alias("answer");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataSubject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataSubject", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL);
    b.class_(false, false, true);
    // extends: PRIAM_LANGUAGE.structure.MainActor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544491");
    b.version(3);
    b.property("age", 0x30f0048592d2bdb3L).type(PrimitiveTypeId.INTEGER).origin("3526323479971544499").done();
    b.property("referenceId", 0x3f0ad7c415365234L).type(PrimitiveTypeId.STRING).origin("4542680411326009908").done();
    b.associate("dsCategory", 0x3f0ad7c4153b8154L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL).optional(false).origin("4542680411326349652").done();
    b.associate("parent", 0x3f0ad7c4153b945aL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdadL).optional(true).origin("4542680411326354522").done();
    b.alias("dataSubject");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataSubjectCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataSubjectCategory", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5799940921481343741");
    b.version(3);
    b.property("dataSubjectCategoryId", 0x2a509229fff45202L).type(PrimitiveTypeId.INTEGER).origin("3049097656815342082").done();
    b.property("locationId", 0x507d8789e725b300L).type(PrimitiveTypeId.STRING).origin("5799940921481343744").done();
    b.alias("dataSubjectCategory");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataSubjectRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataSubjectRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb30c0a81L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262452378241");
    b.version(3);
    b.associate("dataSubject", 0x1f97ffaeb30c0a82L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdabL).optional(false).origin("2276569262452378242").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataType", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5309b4b3bd5290L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/23373094781276816");
    b.version(3);
    b.property("dataTypeId", 0x3c40a36f21039df0L).type(PrimitiveTypeId.INTEGER).origin("4341649738475740656").done();
    b.aggregate("data", 0x1f97ffaeb2ce7798L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L).optional(false).ordered(true).multiple(true).origin("2276569262448342936").done();
    b.alias("dataType");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataUsage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "DataUsage", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411277L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656832631");
    b.version(3);
    b.property("dataUsageId", 0x13b7d324448cf270L).type(PrimitiveTypeId.INTEGER).origin("1420836360181052016").done();
    b.property("hasPersonalUsage", 0x5ed7b73b7b4117c9L).type(PrimitiveTypeId.BOOLEAN).origin("6834132425656833993").done();
    b.property("c", 0x5ed7b73b7b4117cbL).type(PrimitiveTypeId.BOOLEAN).origin("6834132425656833995").done();
    b.property("r", 0x5ed7b73b7b4117ceL).type(PrimitiveTypeId.BOOLEAN).origin("6834132425656833998").done();
    b.property("u", 0x5ed7b73b7b4117d2L).type(PrimitiveTypeId.BOOLEAN).origin("6834132425656834002").done();
    b.property("d", 0x5ed7b73b7b4117d7L).type(PrimitiveTypeId.BOOLEAN).origin("6834132425656834007").done();
    b.associate("data", 0x3c40a36f21039df9L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411269L).optional(false).origin("4341649738475740665").done();
    b.alias("dataUsage");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListCountry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ListCountry", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x4e6350a8b6cd4c08L);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5648447043204369416");
    b.version(3);
    b.aggregate("countries", 0x4e6350a8b6cd4c0bL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b5dL).optional(false).ordered(true).multiple(true).origin("5648447043204369419").done();
    b.alias("List of countries");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListPersonalDataCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ListPersonalDataCategory", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a8L);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/7072058747586032808");
    b.version(3);
    b.aggregate("personalDataCategory", 0x6224fff6288f34a9L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a4L).optional(true).ordered(true).multiple(true).origin("7072058747586032809").done();
    b.alias("ListPersonalDataCategory");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMainActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "MainActor", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.class_(false, true, false);
    // extends: PRIAM_LANGUAGE.structure.Actor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544489");
    b.version(3);
    b.alias("mainActor");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMainActorRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "MainActorRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb3031cc1L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262451793089");
    b.version(3);
    b.associate("actor", 0x1f97ffaeb3031cc2L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L).optional(false).origin("2276569262451793090").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMeasure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Measure", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b9fL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6800078833463032735");
    b.version(3);
    b.property("measureId", 0x5e5ebbabb1377ba0L).type(PrimitiveTypeId.INTEGER).origin("6800078833463032736").done();
    b.property("description", 0x5e5ebbabb1377ba2L).type(PrimitiveTypeId.STRING).origin("6800078833463032738").done();
    b.property("measureType", 0x3d13017cc9130fbcL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377bb8L)).origin("4400862896332148668").done();
    b.property("measureCategory", 0x3d13017cc9130fc0L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377bbdL)).origin("4400862896332148672").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMeasureRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "MeasureRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e7c5L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6986923738720036805");
    b.version(3);
    b.associate("measureRef", 0x60f68a1f3f26e7c6L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b9fL).optional(false).origin("6986923738720036806").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNonPersonalData() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "NonPersonalData", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2615d150e803c810L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2744329693372336144");
    b.version(3);
    b.alias("nonPersonalData");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPRIAM_DB() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "PRIAM_DB", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x824129b34920bc3L);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/586614309276224451");
    b.version(3);
    b.associate("countries", 0x316f9f331d308df6L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x4e6350a8b6cd4c08L).optional(false).origin("3562240872155221494").done();
    b.alias("PRIAM_GDPR");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersonalData() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "PersonalData", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x9b6693a01c08cc8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/699862489961106632");
    b.version(3);
    b.property("dataConservation", 0x9b6693a01c08cdaL).type(PrimitiveTypeId.INTEGER).origin("699862489961106650").done();
    b.property("source", 0x5ed7b73b7b411270L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5547fb75b03f47d2L)).origin("6834132425656832624").done();
    b.property("sourceDetails", 0x3c40a36f21039df2L).type(PrimitiveTypeId.STRING).origin("4341649738475740658").done();
    b.property("isPortable", 0x5e5ebbabb1377b96L).type(PrimitiveTypeId.BOOLEAN).origin("6800078833463032726").done();
    b.associate("personalDataCategory", 0x6224fff6288f34a7L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a4L).optional(false).origin("7072058747586032807").done();
    b.associate("dataSubjectCategory", 0x2661cc24bc0b3327L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL).optional(false).origin("2765716104327934759").done();
    b.alias("personalData");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersonalDataCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "PersonalDataCategory", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x6224fff6288f34a4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/7072058747586032804");
    b.version(3);
    b.property("pdcId", 0x6224fff6288f34a6L).type(PrimitiveTypeId.INTEGER).origin("7072058747586032806").done();
    b.alias("personalDataCateogry");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersonalDataTransfer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "PersonalDataTransfer", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bae1d4fL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/9086395038181498191");
    b.version(3);
    b.property("transferId", 0x7e195c253bae1d50L).type(PrimitiveTypeId.INTEGER).origin("9086395038181498192").done();
    b.aggregate("data", 0x7e195c253bb501a3L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bb9471dL).optional(false).ordered(true).multiple(true).origin("9086395038181949859").done();
    b.aggregate("secondaryActor", 0x7e195c253bc1d457L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bbd8ccaL).optional(false).ordered(true).multiple(true).origin("9086395038182790231").done();
    b.aggregate("processingRef", 0x7e195c253bc1d45aL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x26e217bc0d00c73dL).optional(false).ordered(true).multiple(false).origin("9086395038182790234").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessing() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Processing", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656832578");
    b.version(3);
    b.property("processingId", 0x74fd0aaeb0fbe2baL).type(PrimitiveTypeId.INTEGER).origin("8429905822917321402").done();
    b.property("pt", 0x5ed7b73b7b411247L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x4f5a6cf6560fc2bfL)).origin("6834132425656832583").done();
    b.property("pc", 0x5ed7b73b7b411249L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bde1L)).origin("6834132425656832585").done();
    b.property("createdDate", 0x5ed7b73b7b41124cL).type(PrimitiveTypeId.STRING).origin("6834132425656832588").done();
    b.property("modifiedDate", 0x5ed7b73b7b411250L).type(PrimitiveTypeId.STRING).origin("6834132425656832592").done();
    b.property("endedDate", 0x4d1e5d75ba53ea21L).type(PrimitiveTypeId.STRING).origin("5556981750440389153").done();
    b.aggregate("purposes", 0x5ed7b73b7b4129b5L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411d71L).optional(false).ordered(true).multiple(true).origin("6834132425656838581").done();
    b.aggregate("dataUsage", 0x3c40a36f21039e0aL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411277L).optional(false).ordered(true).multiple(true).origin("4341649738475740682").done();
    b.aggregate("measures", 0x60f68a1f3f26e7c8L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e7c5L).optional(false).ordered(true).multiple(true).origin("6986923738720036808").done();
    b.aggregate("actors", 0x1f97ffaeb2d2c079L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb3031cc1L).optional(false).ordered(true).multiple(true).origin("2276569262448623737").done();
    b.aggregate("processingLink", 0x1f97ffaeb2f18095L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb2db8958L).optional(true).ordered(true).multiple(true).origin("2276569262450638997").done();
    b.alias("processing");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessingAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ProcessingAnnotation", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x500664cd9d79c21fL);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/5766407207167574559");
    b.version(3);
    b.aggregate("measures", 0x3c40a36f20df10c4L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b9fL).optional(true).ordered(true).multiple(true).origin("4341649738473345220").done();
    b.aggregate("processing", 0x500664cd9d79c220L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L).optional(false).ordered(true).multiple(true).origin("5766407207167574560").done();
    b.aggregate("processingTransfer", 0x8eea37654f47a1cL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bae1d4fL).optional(true).ordered(true).multiple(true).origin("643631525387336220").done();
    b.alias("processingAnnotation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessingLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ProcessingLink", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb2db8958L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2276569262449199448");
    b.version(3);
    b.property("typeOfLink", 0x1f97ffaeb2db8959L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x1f97ffaeb2db895bL)).origin("2276569262449199449").done();
    b.associate("processing", 0x1f97ffaeb2feb15eL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L).optional(true).origin("2276569262451503454").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessingRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ProcessingRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x26e217bc0d00c73dL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2801828014617315133");
    b.version(3);
    b.property("consented", 0x5a5b705effb06adaL).type(PrimitiveTypeId.BOOLEAN).origin("6510921239613172442").done();
    b.associate("processing", 0x26e217bc0d022c16L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L).optional(false).origin("2801828014617406486").done();
    b.alias("processing");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessingRequest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "ProcessingRequest", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96ecL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/4648915867537282796");
    b.version(3);
    b.associate("processing", 0x40844459bb3d197fL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L).optional(false).origin("4648915867537316223").done();
    b.alias("processing");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProvider() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Provider", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdacL);
    b.class_(false, false, true);
    // extends: PRIAM_LANGUAGE.structure.MainActor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544492");
    b.version(3);
    b.property("prPhone", 0x30f0048592d2bdc3L).type(PrimitiveTypeId.STRING).origin("3526323479971544515").done();
    b.property("prEmail", 0x30f0048592d2bdc9L).type(PrimitiveTypeId.STRING).origin("3526323479971544521").done();
    b.aggregate("providerAddress", 0x1f97ffaeb2ca28f7L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L).optional(false).ordered(true).multiple(false).origin("2276569262448060663").done();
    b.alias("provider");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPurpose() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Purpose", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411d71L);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6834132425656835441");
    b.version(3);
    b.property("purposeId", 0x1f97ffaeb2d717afL).type(PrimitiveTypeId.INTEGER).origin("2276569262448908207").done();
    b.property("description", 0x5ed7b73b7b411d72L).type(PrimitiveTypeId.STRING).origin("6834132425656835442").done();
    b.property("type", 0x5ed7b73b7b411d74L).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2eea2L)).origin("6834132425656835444").done();
    b.alias("purpose");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRepresentative() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Representative", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff45205L);
    b.class_(false, false, false);
    // extends: PRIAM_LANGUAGE.structure.MainActor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3049097656815342085");
    b.version(3);
    b.property("repPhone", 0x2a509229fff4520bL).type(PrimitiveTypeId.STRING).origin("3049097656815342091").done();
    b.property("repEmail", 0x2a509229fff4520cL).type(PrimitiveTypeId.STRING).origin("3049097656815342092").done();
    b.aggregate("address", 0x2a509229fff4521cL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L).optional(false).ordered(true).multiple(false).origin("3049097656815342108").done();
    b.alias("representative");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Request", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x40844459bb3c96d3L);
    b.class_(false, true, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/4648915867537282771");
    b.version(3);
    b.property("requestId", 0x72cfc7297a249571L).type(PrimitiveTypeId.INTEGER).origin("8273050021459694961").done();
    b.property("claim", 0x40844459bb3c96d4L).type(PrimitiveTypeId.STRING).origin("4648915867537282772").done();
    b.property("claimDate", 0x40844459bb3c96d6L).type(PrimitiveTypeId.STRING).origin("4648915867537282774").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirements() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Requirements", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2661cc24bc0aafbfL);
    b.class_(false, false, true);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/2765716104327901119");
    b.version(3);
    b.associate("dataAtnnotation", 0x2661cc24bc0aafc1L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x3af6325cd45a5aa2L).optional(false).origin("2765716104327901121").done();
    b.associate("processingAnnotation", 0x500664cd9d856f7bL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x500664cd9d79c21fL).optional(false).origin("5766407207168339835").done();
    b.associate("actorAnnotation", 0x2f09b3cf7232109cL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL).optional(false).origin("3389437898128494748").done();
    b.alias("requirement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSecondaryActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "SecondaryActor", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL);
    b.class_(false, false, false);
    // extends: PRIAM_LANGUAGE.structure.Actor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544490");
    b.version(3);
    b.property("saType", 0x60f68a1f3f26e67eL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x60f68a1f3f26e675L)).origin("6986923738720036478").done();
    b.property("phone", 0x5e5ebbabb1377b4dL).type(PrimitiveTypeId.STRING).origin("6800078833463032653").done();
    b.property("email", 0x5e5ebbabb1377b4eL).type(PrimitiveTypeId.STRING).origin("6800078833463032654").done();
    b.property("safeguard", 0x5e5ebbabb1377b55L).type(PrimitiveTypeId.STRING).origin("6800078833463032661").done();
    b.property("safeguardType", 0x2a509229fff451bdL).type(MetaIdFactory.dataTypeId(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451c5L)).origin("3049097656815342013").done();
    b.associate("category", 0x5e5ebbabb1377b92L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL).optional(false).origin("6800078833463032722").done();
    b.aggregate("address", 0x2a509229fff451b3L).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L).optional(false).ordered(true).multiple(false).origin("3049097656815342003").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSecondaryActorCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "SecondaryActorCategory", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/6800078833463032700");
    b.version(3);
    b.property("id", 0x5e5ebbabb1377b7dL).type(PrimitiveTypeId.INTEGER).origin("6800078833463032701").done();
    b.alias("secondaryActorCategory");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSecondaryActorRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "SecondaryActorRef", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x7e195c253bbd8ccaL);
    b.class_(false, false, false);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/9086395038182509770");
    b.version(3);
    b.associate("secondaryActorRef", 0x7e195c253bbd8ccbL).target(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL).optional(false).origin("9086395038182509771").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTutor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PRIAM_LANGUAGE", "Tutor", 0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdadL);
    b.class_(false, false, false);
    // extends: PRIAM_LANGUAGE.structure.MainActor
    b.super_(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda9L);
    b.origin("r:515d5f51-79c9-42c9-bba4-54c97b772d5b(PRIAM_LANGUAGE.structure)/3526323479971544493");
    b.version(3);
    b.property("tutorName", 0x30f0048592d2bdd0L).type(PrimitiveTypeId.STRING).origin("3526323479971544528").done();
    b.alias("tutor");
    return b.create();
  }
}
