package PRIAM_LANGUAGE.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class ActorAnnotationFactory {
  public static class NodeFactory_3562240872144862763 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.actorId$UrlW, SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.nodes(model, CONCEPTS.Actor$CH)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.actorId$UrlW);
        }
      }, true).last(), PROPS.actorId$UrlW) + 1);
    }
  }
  public static class NodeFactory_1266870654838255558 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.addressId$6tGg, SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.nodes(model, CONCEPTS.Address$5x)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.addressId$6tGg);
        }
      }, true).last(), PROPS.addressId$6tGg) + 1);
    }
  }
  public static class NodeFactory_3562240872139996213 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.dataSubjectCategoryId$m11P, SPropertyOperations.getInteger(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(enclosingNode), CONCEPTS.DataSubjectCategory$pH)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.dataSubjectCategoryId$m11P);
        }
      }, true).last(), PROPS.dataSubjectCategoryId$m11P) + 1);
    }
  }
  public static class NodeFactory_3562240872153964676 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.id$dzJQ, SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.nodes(model, CONCEPTS.SecondaryActorCategory$HB)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.id$dzJQ);
        }
      }, true).last(), PROPS.id$dzJQ) + 1);
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty actorId$UrlW = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L, 0x3f0ad7c4153c99b7L, "actorId");
    /*package*/ static final SProperty addressId$6tGg = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x13b7d32444879362L, "addressId");
    /*package*/ static final SProperty dataSubjectCategoryId$m11P = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL, 0x2a509229fff45202L, "dataSubjectCategoryId");
    /*package*/ static final SProperty id$dzJQ = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL, 0x5e5ebbabb1377b7dL, "id");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Actor$CH = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L, "PRIAM_LANGUAGE.structure.Actor");
    /*package*/ static final SConcept Address$5x = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, "PRIAM_LANGUAGE.structure.Address");
    /*package*/ static final SConcept DataSubjectCategory$pH = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL, "PRIAM_LANGUAGE.structure.DataSubjectCategory");
    /*package*/ static final SConcept SecondaryActorCategory$HB = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL, "PRIAM_LANGUAGE.structure.SecondaryActorCategory");
  }
}
