package PRIAM_LANGUAGE.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class ProcessingAnnotation {
  public static class NodeFactory_643120355008353672 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.dataUsageId$IE5E, SPropertyOperations.getInteger(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(enclosingNode), CONCEPTS.DataUsage$nH)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.dataUsageId$IE5E);
        }
      }, true).last(), PROPS.dataUsageId$IE5E) + 1);
    }
  }
  public static class NodeFactory_643120355008343340 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.processingId$d2f, SPropertyOperations.getInteger(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(enclosingNode), CONCEPTS.Processing$5F)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.processingId$d2f);
        }
      }, true).last(), PROPS.processingId$d2f) + 1);
    }
  }
  public static class NodeFactory_643120355009055850 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.purposeId$WXGG, SPropertyOperations.getInteger(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(enclosingNode), CONCEPTS.Purpose$tN)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.purposeId$WXGG);
        }
      }, true).last(), PROPS.purposeId$WXGG) + 1);
    }
  }
  public static class NodeFactory_643120355009053900 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.measureId$dVuQ, SPropertyOperations.getInteger(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(enclosingNode), CONCEPTS.Measure$t5)).sort(new ISelector<SNode, Integer>() {
        public Integer select(SNode it) {
          return SPropertyOperations.getInteger(it, PROPS.measureId$dVuQ);
        }
      }, true).last(), PROPS.measureId$dVuQ) + 1);
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty dataUsageId$IE5E = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411277L, 0x13b7d324448cf270L, "dataUsageId");
    /*package*/ static final SProperty processingId$d2f = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L, 0x74fd0aaeb0fbe2baL, "processingId");
    /*package*/ static final SProperty purposeId$WXGG = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411d71L, 0x1f97ffaeb2d717afL, "purposeId");
    /*package*/ static final SProperty measureId$dVuQ = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b9fL, 0x5e5ebbabb1377ba0L, "measureId");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataUsage$nH = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411277L, "PRIAM_LANGUAGE.structure.DataUsage");
    /*package*/ static final SConcept Processing$5F = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411242L, "PRIAM_LANGUAGE.structure.Processing");
    /*package*/ static final SConcept Purpose$tN = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5ed7b73b7b411d71L, "PRIAM_LANGUAGE.structure.Purpose");
    /*package*/ static final SConcept Measure$t5 = MetaAdapterFactory.getConcept(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b9fL, "PRIAM_LANGUAGE.structure.Measure");
  }
}
