package PRIAM_LANGUAGE.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class ActorAnnotation_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("/* insert provider */");
    tgs.newLine();
    tgs.append("insert into Address(address_id, street_number, street_name, postal_code, city, complement ) values (");
    tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.addressId$6tGg) + "");
    tgs.append(", ");
    tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.streetNumber$GMX8) + "");
    tgs.append("' , '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.streetName$GNTc));
    tgs.append("' , '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.PostalCode$3e1a) + "");
    tgs.append(", '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.city$3egb));
    tgs.append("' , '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.complement$GTZA));
    tgs.append("');");
    tgs.newLine();

    tgs.append("insert into Provider(provider_id, provider_name, provider_address, provider_phone, provider_email, country_id) values (");
    tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), PROPS.actorId$UrlW) + "");
    tgs.append(", '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), PROPS.name$MnvL));
    tgs.append("' , '");
    tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.providerAddress$1bju), PROPS.addressId$6tGg) + "");
    tgs.append(", '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), PROPS.prPhone$mJ6x));
    tgs.append("' , '");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), PROPS.prEmail$mPrW));
    tgs.append(", '");
    tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.provider$_6Hp), LINKS.country$PakR), PROPS.countryId$aJCd) + "");
    tgs.append("');");
    tgs.newLine();

    tgs.append("/* insert DPO */");
    tgs.newLine();
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl) != null)) {
      tgs.append("insert into Address(address_id, street_number, street_name, postal_code, city, complement ) values (");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.addressId$6tGg) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.streetNumber$GMX8) + "");
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.streetName$GNTc));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.PostalCode$3e1a) + "");
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.city$3egb));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.complement$GTZA));
      tgs.append("');");
      tgs.newLine();

      tgs.append("insert into DPO(dpo_id, dpo_name, dpo_address, dpo_phone, dpo_email, country_id) values (");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), PROPS.actorId$UrlW) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), PROPS.name$MnvL));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.dpoAddress$DlTn), PROPS.addressId$6tGg) + "");
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), PROPS.dpoPhone$aYCf));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), PROPS.dpoEmail$aYRg));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dpo$_kMl), LINKS.country$PakR), PROPS.countryId$aJCd) + "");
      tgs.append("');");
      tgs.newLine();

    }

    tgs.append("/* insert representative */");
    tgs.newLine();
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL) != null)) {
      tgs.append("insert into Address(address_id, street_number, street_name, postal_code, city, complement ) values (");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.addressId$6tGg) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.streetNumber$GMX8) + "");
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.streetName$GNTc));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.PostalCode$3e1a) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.city$3egb));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.complement$GTZA));
      tgs.append("');");
      tgs.newLine();

      tgs.append("insert into Representative(representative_id, representative_name, representative_address, representative_phone, representative_email, country_id) values (");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), PROPS.actorId$UrlW) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), PROPS.name$MnvL));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.address$$Nhx), PROPS.addressId$6tGg) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), PROPS.repPhone$yhBK));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), PROPS.repEmail$yhQL));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.representative$_rmL), LINKS.country$PakR), PROPS.countryId$aJCd) + "");
      tgs.append("');");
      tgs.newLine();

    }

    tgs.append("/* insert data subject categories */");
    tgs.newLine();
    for (SNode d : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.dataSubjectCategories$$YXS))) {
      tgs.append("insert into DataSubjectCategory(data_subject_category_id, data_subject_category_name, location_id) values (");
      tgs.append(SPropertyOperations.getInteger(d, PROPS.dataSubjectCategoryId$m11P) + "");
      tgs.append(", '");
      tgs.append(SPropertyOperations.getString(d, PROPS.name$MnvL));
      tgs.append("' , '");
      tgs.append(SPropertyOperations.getString(d, PROPS.locationId$tqgS));
      tgs.append("');");
      tgs.newLine();
    }

    tgs.append("/* insert secondary actor categories */");
    tgs.newLine();
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.secodaryActorCategories$$ZEV)).isNotEmpty()) {
      for (SNode s : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.secodaryActorCategories$$ZEV))) {
        tgs.append("insert into SecondaryActorCategory(secondary_actor_category_id, secondary_actor_category_name) values (");
        tgs.append(SPropertyOperations.getInteger(s, PROPS.id$dzJQ) + "");
        tgs.append(", '");
        tgs.append(SPropertyOperations.getString(s, PROPS.name$MnvL));
        tgs.append("');");
        tgs.newLine();
      }

    }
    //  insert secondary actors
    tgs.append("/* insert secondary actors */");
    tgs.newLine();
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.secondaryActors$_5yk)).isNotEmpty()) {
      for (SNode s : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.secondaryActors$_5yk))) {
        tgs.append("insert into Address(address_id, street_number, street_name, postal_code, city, complement ) values (");
        tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.addressId$6tGg) + "");
        tgs.append(", '");
        tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.streetNumber$GMX8) + "");
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.streetName$GNTc));
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.PostalCode$3e1a) + "");
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.city$3egb));
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.complement$GTZA));
        tgs.append("');");
        tgs.newLine();

        tgs.append("insert into SecondaryActor(secondary_actor_id, secondary_actor_type, secondary_actor_name, secondary_actor_address, secondary_actor_phone, secondary_actor_email,safeguard_type, secondary_actor_category_id, country_id) values (");
        tgs.append(SPropertyOperations.getInteger(s, PROPS.actorId$UrlW) + "");
        tgs.append(", '");
        tgs.append(SPropertyOperations.getEnum(s, PROPS.saType$5S3C).toString());
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(s, PROPS.name$MnvL));
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(s, LINKS.address$iOv7), PROPS.addressId$6tGg) + "");
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(s, PROPS.phone$OOdx) + "");
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getString(s, PROPS.email$OOsy));
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getEnum(s, PROPS.safeguardType$iVKA).toString());
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(s, LINKS.category$RZC4), PROPS.id$dzJQ) + "");
        tgs.append("' , '");
        tgs.append(SPropertyOperations.getInteger(SLinkOperations.getTarget(s, LINKS.country$PakR), PROPS.countryId$aJCd) + "");
        tgs.append("');");
        tgs.newLine();
      }

    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink provider$_6Hp = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff4522dL, "provider");
    /*package*/ static final SContainmentLink providerAddress$1bju = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdacL, 0x1f97ffaeb2ca28f7L, "providerAddress");
    /*package*/ static final SReferenceLink country$PakR = MetaAdapterFactory.getReferenceLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L, 0x5e5ebbabb1377b6dL, "country");
    /*package*/ static final SContainmentLink dpo$_kMl = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff4523fL, "dpo");
    /*package*/ static final SContainmentLink dpoAddress$DlTn = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b6fL, 0x2a509229fff451fdL, "dpoAddress");
    /*package*/ static final SContainmentLink representative$_rmL = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff45246L, "representative");
    /*package*/ static final SContainmentLink address$$Nhx = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff45205L, 0x2a509229fff4521cL, "address");
    /*package*/ static final SContainmentLink dataSubjectCategories$$YXS = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff45221L, "dataSubjectCategories");
    /*package*/ static final SContainmentLink secodaryActorCategories$$ZEV = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff45224L, "secodaryActorCategories");
    /*package*/ static final SContainmentLink address$iOv7 = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x2a509229fff451b3L, "address");
    /*package*/ static final SReferenceLink category$RZC4 = MetaAdapterFactory.getReferenceLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x5e5ebbabb1377b92L, "category");
    /*package*/ static final SContainmentLink secondaryActors$_5yk = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff45228L, "secondaryActors");
  }

  private static final class PROPS {
    /*package*/ static final SProperty addressId$6tGg = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x13b7d32444879362L, "addressId");
    /*package*/ static final SProperty streetNumber$GMX8 = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x718a863b65af79ecL, "streetNumber");
    /*package*/ static final SProperty streetName$GNTc = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x718a863b65af79f0L, "streetName");
    /*package*/ static final SProperty PostalCode$3e1a = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x5e5ebbabb1377b4bL, "PostalCode");
    /*package*/ static final SProperty city$3egb = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x5e5ebbabb1377b4cL, "city");
    /*package*/ static final SProperty complement$GTZA = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff451b6L, 0x718a863b65af79f5L, "complement");
    /*package*/ static final SProperty actorId$UrlW = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bda8L, 0x3f0ad7c4153c99b7L, "actorId");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty prPhone$mJ6x = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdacL, 0x30f0048592d2bdc3L, "prPhone");
    /*package*/ static final SProperty prEmail$mPrW = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdacL, 0x30f0048592d2bdc9L, "prEmail");
    /*package*/ static final SProperty countryId$aJCd = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b5dL, 0x5e5ebbabb1377b60L, "countryId");
    /*package*/ static final SProperty dpoPhone$aYCf = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b6fL, 0x5e5ebbabb1377b74L, "dpoPhone");
    /*package*/ static final SProperty dpoEmail$aYRg = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b6fL, 0x5e5ebbabb1377b75L, "dpoEmail");
    /*package*/ static final SProperty repPhone$yhBK = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff45205L, 0x2a509229fff4520bL, "repPhone");
    /*package*/ static final SProperty repEmail$yhQL = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff45205L, 0x2a509229fff4520cL, "repEmail");
    /*package*/ static final SProperty dataSubjectCategoryId$m11P = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL, 0x2a509229fff45202L, "dataSubjectCategoryId");
    /*package*/ static final SProperty locationId$tqgS = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x507d8789e725b2fdL, 0x507d8789e725b300L, "locationId");
    /*package*/ static final SProperty id$dzJQ = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x5e5ebbabb1377b7cL, 0x5e5ebbabb1377b7dL, "id");
    /*package*/ static final SProperty saType$5S3C = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x60f68a1f3f26e67eL, "saType");
    /*package*/ static final SProperty phone$OOdx = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x5e5ebbabb1377b4dL, "phone");
    /*package*/ static final SProperty email$OOsy = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x5e5ebbabb1377b4eL, "email");
    /*package*/ static final SProperty safeguardType$iVKA = MetaAdapterFactory.getProperty(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x30f0048592d2bdaaL, 0x2a509229fff451bdL, "safeguardType");
  }
}
