package PRIAM_LANGUAGE.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.List;
import PRIAM_LANGUAGE.behavior.DataAnnotation__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class Requirements_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("--------------------------- Actor part -----------------------------");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data subject: ");
    tgs.newLine();
    tgs.append("As a data subject, I want to have access to the contact details of the DPO (Data Protection Officer)");
    tgs.newLine();
    tgs.append("As a data subject, I want to have access to the contact details of the data controller / representative");
    tgs.newLine();
    tgs.append("As a data subject, I want a legal guardian to be appointed, so that I can be sure that my rights ");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of the data consumers/categories of data consumers.");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data controller: ");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to document my contact details  / those of the representative");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to document the DPO's contact details");
    tgs.newLine();
    tgs.append("As data controller, I want to document the contact details of the data consumers (recipient, third party and data processor)");
    tgs.newLine();
    tgs.append("As a data controller, i want to list the categories of data subject");
    tgs.newLine();
    tgs.newLine();
    tgs.append("--------------------------- Data part -----------------------------");
    tgs.newLine();
    for (SNode dsc : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.actorAnnotation$$uzY), LINKS.dataSubjectCategories$$YXS)).distinct()) {
      List<String> listDataByDSC = DataAnnotation__BehaviorDescriptor.getDataListByDSCategory_id2W9GWXMd5x9.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dataAtnnotation$NG_c), SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      String dataList = DataAnnotation__BehaviorDescriptor.Display_id2W9GWXMeA2H.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dataAtnnotation$NG_c), listDataByDSC);

      tgs.append("Data subject ");
      tgs.append(SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      tgs.append(" :");
      tgs.newLine();
      tgs.newLine();
      tgs.append("As a ");
      tgs.append(SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      tgs.append(" , I want to be informed about which personal data is collected, processed and shared.");
      tgs.newLine();
      tgs.append("As a ");
      tgs.append(SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      tgs.append(", I want to be informed about the categories of my personal data.");
      tgs.newLine();
      tgs.append("As a ");
      tgs.append(SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      tgs.append(" , I want to be informed of the source of my personal data: ");
      tgs.append(dataList);
      tgs.newLine();
      tgs.append("As a ");
      tgs.append(SPropertyOperations.getString(dsc, PROPS.name$MnvL));
      tgs.append(", I want to be informed about how long my personal data: [");
      tgs.append(dataList);
      tgs.append(" ] will be kept.(retention period).");
      tgs.newLine();

    }

    tgs.append("Data controller: ");
    tgs.newLine();
    tgs.append("As a data controller, I want to ensure that my organization has mechanisms in place to keep personal data up to date and accurate.");
    tgs.newLine();
    tgs.append("As data controller, I want to list the data in my application and their status (personal or non-personal).");
    tgs.newLine();
    tgs.append("As a data controller, I want to document for each piece of personal data, its retention period, its source, its category, as well as the category \nof data subject to which it belongs that ensure adequate and transparent documentation.\"");
    tgs.newLine();

    tgs.append("--------------------------- Processing part -----------------------------");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data subject: ");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of any personal processing performed on my personal data.");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of the legal basis for my processings.");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of the purposes for which my personal processing has been performed.");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed about the transfer of my personal data within or outside the European Union, including the data transferred, \nthe purpose of the transfer and the receiving entity\"");
    tgs.newLine();
    tgs.append("As a data subject I must be informed of the technical and organizational measures taken to guarantee the protection of my personal data. ");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of any further processing of my personal data, including the purposes of such processing");
    tgs.newLine();
    tgs.append("As a data subject I want to be notified of any changes concerning my personal data and data processing");
    tgs.newLine();
    tgs.append("\"As a data subject, I want to understand whether providing my personal data is a legal or contractual obligation, and what the consequences are if I choose not to\n provide this data, so that I can make decisions about disclosing my personal data.\"");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data controller: ");
    tgs.newLine();
    tgs.append("As a data controller, I want to ensure that my organization complies with the data minimization principles by collecting only the information that is \nstrictly necessary for the specific purposes of the processing. purposes of the processing.\"");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to document the details of each data processing operation, including its legal basis, its purpose(s) and \nthe associated technical and organizational measures.\"\n\n");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to document the data required for each processing operation (data usage table)");
    tgs.newLine();
    tgs.append("As a data controller I want to be able to document all transfers, including the data consumer and the data to be transferred.");
    tgs.newLine();
    tgs.append("\"As a data controller, I want to be able to add and perform a processing operation with the same purpose as another, where further\n processing is necessary, without obtaining additional consent from data subjects.\"");
    tgs.newLine();
    tgs.append("\"As a controller, I want to ensure that my organization has complete documentation of processing activities, including purposes, \ncategories of data, and recipients (processing record).\"");
    tgs.newLine();
    tgs.append("As a data controller, I want to ensure that my organization carries out Data Protection Impact Assessments (DPIA)");
    tgs.newLine();
    tgs.newLine();
    tgs.append("--------------------------- Consent part -----------------------------");
    tgs.append("Data subject: ");
    tgs.newLine();
    tgs.append("As a data subject I want to give my explicit consent for each specific processing of my personal data");
    tgs.newLine();
    tgs.append("As a data subject, I want to be able to change my consent preferences at any time.");
    tgs.newLine();
    tgs.append("As a data subject, I want to be able to refuse that my data to be used for profiling purposes or to be the subject of automated decisions.");
    tgs.newLine();
    tgs.append("As a data subject, I want the process of collecting my consent to be transparent and easy to understand");
    tgs.newLine();
    tgs.append("As a data subject I want to access/download my contract");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data controller: ");
    tgs.newLine();
    tgs.append("As a data controller, I want to document and record individuals' consent so that I can demonstrate it if necessary");
    tgs.newLine();
    tgs.append("As a data controller, I want to ensure that my organization complies with specific rules regarding the consent of minors, where applicable");
    tgs.newLine();
    tgs.append("As a data controller, I want to access or download a data subject's contract.");
    tgs.newLine();
    tgs.append("As a data controller I want to generate, in a machine-readable format, the consents of the data subjects to the processing performed by the secondary actors. ");
    tgs.newLine();
    tgs.newLine();
    tgs.append("--------------------------- Right part -----------------------------");
    tgs.append("Data subject:");
    tgs.newLine();
    tgs.append("As a [data subject] I want to acces to all my personal data [data list]");
    tgs.newLine();
    tgs.append("As a [data subject], I want to be able to object to processing [processing list].");
    tgs.newLine();
    tgs.append("As a [data subject], I want to be able to restrict processing [processing list].");
    tgs.newLine();
    tgs.append("As a [data subject] I want to give or not and withdraw my consent anytime for [ ] SO THAT I exercise my right to consent");
    tgs.newLine();
    tgs.append("As a  [data subject] I want to rectify any of my personal data [data list] SO THAT I exercise my right to rectify personal data ");
    tgs.newLine();
    tgs.append("AS [data subject] I want to erase any of my personal data  [data list] SO THAT I exercise my right to be forgotten ");
    tgs.newLine();
    tgs.append("As a [data subject] I want to obtain any of my personal data [data list] SO THAT I exercise my right to personal data portability");
    tgs.newLine();
    tgs.append("As a [data subject] I want to know all information about my personal data and their processing SO THAT I enforce my right to knowledge");
    tgs.newLine();
    tgs.append("As a [data subject], I want my personal data to be deleted when legally required to do so");
    tgs.newLine();
    tgs.append("As a [data subject], I want to be informed of my rights");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed of my right to lodge a complaint with a supervisory authority, ");
    tgs.newLine();
    tgs.append("As data subject I want to be notified when the limitation is lifted ");
    tgs.newLine();
    tgs.append("As a data subject I want to be notified of responses to my requests to enforce my rights");
    tgs.newLine();
    tgs.append("As the data subject, I want to be informed of the answers given to my requests, as well as the date and justification.");
    tgs.newLine();
    tgs.newLine();
    tgs.append("Data controller:");
    tgs.newLine();
    tgs.append("As a data controller, I want to ensure that the time limits (not exceeding 1 month) for responding to requests to enforce the rights of data subjects are respected.");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to request additional information from my dataSubjects if necessary");
    tgs.newLine();
    tgs.append("As data controller, I want to be notified when data subjects make a request to enforce their rights.");
    tgs.newLine();
    tgs.append("As a data controller I want to notify data consumers of any changes that affect the personal data of data subjects");
    tgs.newLine();
    tgs.newLine();
    tgs.append("--------------------------- Breach part -----------------------------");
    tgs.newLine();
    tgs.append("Data subject:");
    tgs.newLine();
    tgs.append("\"As a data subject I want be informed of the technical and organizational measures taken to guarantee the protection of my personal data \nthat has been breached.\"");
    tgs.newLine();
    tgs.append("As a [data subject], I want to be informed of the data that has been breached and the consequences of the breach.");
    tgs.newLine();
    tgs.append("As a data subject, I want to be informed in the event of a breach of my personal data.");
    tgs.newLine();
    tgs.newLine();
    tgs.append("data controller:");
    tgs.newLine();
    tgs.append("As a data controller, I want to to maintain a data breach record.");
    tgs.newLine();
    tgs.append("As a data controller, I want to be able to inform the supervisory authority in the event of a data breach of personal data");
    tgs.newLine();
    tgs.append("\"As a data controller, I want to document all information related to the breach, including the data subjects affected, the data breached, \nthe consequences and the measures taken.\"");
    tgs.newLine();
    tgs.append("As a data controller I want to document the reasons why the supervisory authority and/or data subjects have not been notified.");
    tgs.newLine();
    tgs.append("as a data controller i want to be alerted when notification of the supervisory authority is required ");
    tgs.newLine();
    tgs.append("Secondary actor:");
    tgs.newLine();
    tgs.append("\"As a secondary actor, I want to document all information related to the breach, including the data subjects affected, the data breached, \nthe consequences and the measures taken.\"");
    tgs.newLine();


  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink dataAtnnotation$NG_c = MetaAdapterFactory.getReferenceLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2661cc24bc0aafbfL, 0x2661cc24bc0aafc1L, "dataAtnnotation");
    /*package*/ static final SReferenceLink actorAnnotation$$uzY = MetaAdapterFactory.getReferenceLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2661cc24bc0aafbfL, 0x2f09b3cf7232109cL, "actorAnnotation");
    /*package*/ static final SContainmentLink dataSubjectCategories$$YXS = MetaAdapterFactory.getContainmentLink(0xe02dfeab630f4f6dL, 0x86a8a0833a3f70fcL, 0x2a509229fff4521eL, 0x2a509229fff45221L, "dataSubjectCategories");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
